Repository Contrastellar/OpossumBot, pull requests merged in 2022-04, with the labels that each got.

#3 ethan's day 1 changes.
  README.md
Labels: enhancement

#4 Various spellchecks for fun
  README.md
Labels: documentation

#7 UNTESTED rudimentary if statement commands.
  src/commands.js
Labels: enhancement, good first issue
